[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "qrcode"
version = "7.5.dev0"
packages = [{include = "qrcode"}]
description = "QR Code image generator"
authors = ["Lincoln Loop <info@lincolnloop.com>"]
license = "BSD"
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.7"
colorama = {version = "*", platform = "win32"}
pypng = "*"
pillow = {version = ">=9.1.0", optional = true}

[tool.poetry.extras]
pil = ["pillow"]

[tool.poetry.group.dev.dependencies]
pytest = {version = "*"}
pytest-cov = {version = "*"}